### ISSUE TITLE
Keep original source folder name

### ISSUE THREAD

**Issue by Pharmtech78** [PersistentCloud/immich-webdav-wrapper#1]
I'm trying to use this for Dynaframe and i was wondering if there is a way to keep the source album name? What's happening is once synced i get an image and video folder instead of the album name. I'm no good at editing scripts. Any help would be appreciated.

**Comment by PersistentCloud** [comment]
Do I understand you correctly and you do not want the files to be split up again into the subfolders Images/Video, but rather all files to be located directly within the folder named after the album?

This should be an easy task, but I need to find the time, which will take some time

**Comment by Pharmtech78** [comment]
> Do I understand you correctly and you do not want the files to be split up again into the subfolders Images/Video, but rather all files to be located directly within the folder named after the album?
> 
> This should be an easy task, but I need to find the time, which will take some time

Spot on, that's correct...keep the folder named after the album. No problem, whenever you get some time. Thank you so much!

**Comment by PersistentCloud** [comment]
Latest version pushed to repository is 1.1.0
